### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by zhouwenlu** [haofeixu/aanet#56]
运行指令时出现这样的错误：error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device,哪位大神可以帮忙讲解一下呢，我的微信号是15033351767，谢谢

**Comment by flow-specter** [comment]
您好，我也遇到了同样的问题，请问解决了吗

**Comment by Jack47746** [comment]
你好，请问你们解决了这个问题嘛?

> 您好，我也遇到了同样的问题，请问解决了吗



> 运行指令时出现这样的错误：error in modulated_deformable_im2col_cuda: no kernel image is available for execution on the device,哪位大神可以帮忙讲解一下呢，我的微信号是15033351767，谢谢

**Comment by haofeixu** [comment]
Hi all, sorry for the late response.

If this issue is still relavant to you, I would suggest to try our new GMStereo model: https://haofeixu.github.io/unimatch/ & https://github.com/autonomousvision/unimatch. No CUDA op is required. A [Colab demo](https://colab.research.google.com/drive/1r5m-xVy3Kw60U-m5VB-aQ98oqqg_6cab?usp=sharing) is also provided to try our model in your browser. Hope it helps, thanks.
