### ISSUE TITLE
Cannot install environment and deform_conv in Google colab 

### ISSUE THREAD

**Issue by hubery4** [haofeixu/aanet#67]
Hi @haofeixu ,

Have you ever tried install and run it in google colab? It always has some installation problem. Could you give me some suggestions on how to run the network in Colab?

Thank you

**Comment by haofeixu** [comment]
Hi @hubery4 , unfortunately I haven't tried on colab.

**Comment by mariocyrus** [comment]
Hi @hubery4 tried also with Google Colab and that was quite a nigthmare. However it was very symple on a competitor called Paperspace Gradient (in a prebuild instance with Pytorch 1.8). Buuut... after that there is a problem with downloading the sets of images because of the low (from the server side) downloading speed and the huge size of these libraries...

I'm currently working off the cloud so...

**Comment by Jack47746** [comment]
hi，Did you solve this problem？

**Comment by Jack47746** [comment]
> Hi @haofeixu ,
> 
> Have you ever tried install and run it in google colab? It always has some installation problem. Could you give me some suggestions on how to run the network in Colab?
> 
> Thank you
