### ISSUE TITLE
error in modulated_deformable_im2col_cuda: invalid device function

### ISSUE THREAD

**Issue by xzjzsa** [haofeixu/aanet#73]

**Comment by Jack47746** [comment]
Hi，Did you solve this problem？

**Comment by haofeixu** [comment]
Hi all, sorry for the late response.

If this issue is still relavant to you, I would suggest to try our new GMStereo model: https://haofeixu.github.io/unimatch/ & https://github.com/autonomousvision/unimatch. No CUDA op is required. A [Colab demo](https://colab.research.google.com/drive/1r5m-xVy3Kw60U-m5VB-aQ98oqqg_6cab?usp=sharing) is also provided to try our model in your browser. Hope it helps, thanks.
